version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: kimberly-nginx-prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    networks:
      - kimberly-net
    depends_on:
      - app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kimberly-app-prod
    restart: unless-stopped
    env_file:
      - .env.prod
    networks:
      - kimberly-net
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres:15-alpine
    container_name: kimberly-postgres-prod
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kimberly-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    container_name: kimberly-redis-prod
    restart: unless-stopped
    networks:
      - kimberly-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres-backup:
    image: prodrigest/postgres-backup-local
    container_name: kimberly-postgres-backup-prod
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - postgres_backups:/backups
    networks:
      - kimberly-net
    environment:
      POSTGRES_HOST: postgres
      # Other POSTGRES variables (DB, USER, PASSWORD) are loaded from env_file
      SCHEDULE: '@daily' # Run a backup every day at midnight
      BACKUP_KEEP_DAYS: 7 # Keep the last 7 daily backups
      BACKUP_KEEP_WEEKS: 4 # Keep the last 4 weekly backups
      BACKUP_KEEP_MONTHS: 6 # Keep the last 6 monthly backups
    depends_on:
      - postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  kimberly-net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  postgres_backups:
    driver: local
  certbot_conf:
    driver: local
  certbot_www:
    driver: local
