# Versión de compose es declarada por el comando, no es necesaria en el archivo.
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rutero-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    # Carga las variables del .env para que estén disponibles en el contenedor en ejecución
    env_file:
      - .env
