-- Initial schema: tables and types

CREATE TYPE public.app_role AS ENUM ('supervisor', 'mercaderista', 'admin');

CREATE TABLE public.puntos_de_venta (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  nombre TEXT NOT NULL,
  direccion TEXT,
  ciudad TEXT,
  latitud REAL,
  longitud REAL
);
COMMENT ON TABLE public.puntos_de_venta IS 'Almacena los puntos de venta a visitar, incluyendo coordenadas.';

CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  updated_at TIMESTAMPTZ,
  full_name TEXT,
  role app_role NOT NULL DEFAULT 'mercaderista'
);
COMMENT ON TABLE public.profiles IS 'Información de perfil público para cada usuario.';

CREATE TABLE public.rutas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  fecha DATE NOT NULL,
  mercaderista_id UUID REFERENCES public.profiles(id),
  puntos_de_venta_ids BIGINT[] NOT NULL
);
COMMENT ON TABLE public.rutas IS 'Almacena las rutas diarias para cada mercaderista.';

CREATE TABLE public.visitas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  ruta_id BIGINT REFERENCES public.rutas(id) ON DELETE CASCADE,
  punto_de_venta_id BIGINT REFERENCES public.puntos_de_venta(id) ON DELETE CASCADE,
  mercaderista_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  check_in_at TIMESTAMPTZ,
  check_out_at TIMESTAMPTZ,
  estado TEXT DEFAULT 'Pendiente' NOT NULL,
  observaciones TEXT,
  url_foto TEXT
);
COMMENT ON TABLE public.visitas IS 'Registra cada visita, su estado y el feedback del mercaderista.';

