-- Paso 0: Eliminar el trigger y la función que dependen de la columna a eliminar
-- El trigger se encuentra en la migración 010.
DROP TRIGGER IF EXISTS trg_validate_pdv_ids ON public.rutas;
DROP FUNCTION IF EXISTS public.validate_pdv_ids_exist();

-- También eliminamos el índice GIN de la migración 011.
DROP INDEX IF EXISTS idx_rutas_puntos_de_venta_ids;

-- Paso 1: Crear la tabla de unión (junction table) para la relación N:M
CREATE TABLE public.ruta_pdv (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ruta_id BIGINT NOT NULL REFERENCES public.rutas(id) ON DELETE CASCADE,
  pdv_id BIGINT NOT NULL REFERENCES public.puntos_de_venta(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  UNIQUE (ruta_id, pdv_id) -- Evita duplicados de PDV en la misma ruta
);

COMMENT ON TABLE public.ruta_pdv IS 'Tabla de unión para enlazar rutas y puntos_de_venta, estableciendo una relación muchos-a-muchos.';

-- Asegurar que solo usuarios autorizados puedan manipular la tabla
ALTER TABLE public.ruta_pdv ENABLE ROW LEVEL SECURITY;

-- Otorgar permisos a los roles de la aplicación
GRANT ALL ON TABLE public.ruta_pdv TO postgres;
GRANT ALL ON TABLE public.ruta_pdv TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.ruta_pdv TO authenticated;


-- Paso 2: Eliminar la columna de array obsoleta de la tabla de rutas
ALTER TABLE public.rutas
DROP COLUMN puntos_de_venta_ids;
